### ISSUE TITLE
To use the amazonlinux image on AzureDevOps requires `adduser`

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docker#178]
@kiazhi 	@RDIL 	
How do you feel about adding `adduser` to the amazonlinux image?

@darwinJS
Not sure if you have any input?

**Comment by RDIL** [comment]
Did you mean to put azurelinux in the title?  Also I have mixed opinions about this.

**Comment by TravisEz13** [comment]
no... third time is a charm

**Comment by kiazhi** [comment]
Actually, I have no issue if you are planning to add `ec2-user` because that is the only account by default that can log in remotely using SSH; this account also has sudo privileges.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-ami-basics.html

If the plan to `adducer` is other than `ec2-user`, I will have mixed opinions about it.

**Comment by TravisEz13** [comment]
I would not add any user in the image unless someone files an issue.  Azure DevOps adds it's own user at run time and switches to it.  They just expect the utility to be there.  With the various distros of linux, I think that is reasonable.

**Comment by TravisEz13** [comment]
Done in #202

**Comment by DarwinJS** [comment]
@TravisEz13 - sorry I'm very late to the game here.  IMO AWS is a little too obsessive about minimalizing all their Amazon Linux 2 distros.  We have to add back stuff like wget to container **host** images (ECS Optimized).  Of course their container configuration is the most minimalized of all.

So that I can do tests of fuller builds on local docker, I now do monthly builds of Amazon Linux 2 containers that have a fuller distribution:

darwinjs/amazonlinux2ec2build

I also do two that include powershell - but you are trying to test installing that.

**Comment by TravisEz13** [comment]
We concluded that we should keep a minimal image with powershell, then a test-deps image that will include all the test-depenecies to run in azure devops pipelines.
The image is up here:  https://cloud.docker.com/u/pshorg/repository/docker/pshorg/powershellcommunity-test-deps

The base image is here: https://cloud.docker.com/u/pshorg/repository/docker/pshorg/powershellcommunity
