### ISSUE TITLE
Why CMD over ENTRYPOINT in Dockerfiles

### ISSUE THREAD

**Issue by AceHack** [PowerShell/PowerShell-Docker#274]
I'm just trying to understand better why choose CMD over ENTRYPOINT in your docker files?

**Comment by RDIL** [comment]
Not quite sure, that doesn't make much sense actually.

**Comment by RDIL** [comment]
Closing as this is resolved and hasn't had activity for a month.

**Comment by AceHack** [comment]
This is not really resolved, just never received an answer.

**Comment by TravisEz13** [comment]
Changing the entry point limits how the container could be used.  See
https://github.com/PowerShell/PowerShell-Docker/issues/274#issuecomment-361087573
and 
https://github.com/PowerShell/PowerShell-Docker/issues/274#issuecomment-361068634

**Comment by AceHack** [comment]
From the comment you posted
In contrast, ENTRYPOINT should be used in scenarios where you want the container to behave exclusively as if it were the executable it's wrapping. That is, when you don't want or expect the user to override the executable you've specified.

This is the exact scenario of pwsh.  It should be entry point.

**Comment by TravisEz13** [comment]
Exactly, that is not the scenario.  Thanks for pointing out why it should not be the entry point.

**Comment by AceHack** [comment]
That IS exactly the scenario of pwsh.  You are saying the opposite of me.

**Comment by TravisEz13** [comment]
This change was already tried and it broke existing automation.  I need enough data that this is what all of the community wants before I will make this change.  My assumption is that they don't want to be broken, without concrete data otherwise.

It maybe your scenario, but it would limit even how you could use the container. I could not even test the container without overriding the entrypoint.

1) Any environment provided by the default shell would not be picked up introducing regressions.
2) in many scenarios, pwsh would be launched twice, increasing memory consumption (as both the entry point and the CMD,) which may seem minor, but is a significant consideration in many container workloads.

I don't see anything that this would reasonably allow that you cannot do today in a reasonable fashion.
