### ISSUE TITLE
Docker tags with powershell patch number

### ISSUE THREAD

**Issue by viceice** [PowerShell/PowerShell-Docker#720]
### Summary of the new feature / enhancement

previously every powershell patch release was taged and published until v7.2.2.
I used renovatebot to updated to every patch release, but since some month the patch tags like `7.2.2-nanoserver-ltsc2022`  are no longer published.

So please publish those again.

sample:
https://github.com/visualon/docker-drone-git/blob/8844ff50e6318d4caccb4d0c8c4285ad57ad1ad3/windows/Dockerfile.2022#L9

**Comment by TravisEz13** [comment]
What is the purpose of publishing those tags?

We have been asked to only publish tags which we can support on an ongoing basis.  Since, a patch is basically not supported after the next patch is released, I don't see the purpose.

If you want to pin to an image, the guidance from MCR is to get the tag for the current tag, and pin to that.

**Comment by viceice** [comment]
Without patch tags it's not possible to rollback to an older patch because it's not possible to find the digest for that.
We're using renovate to automatically update and we like to be informed about any patch updates.

**Comment by TravisEz13** [comment]
Please record the hashes of any patches you want to roll back to.  The approach you are suggesting would not work because we MUST delete tags with issues.  So, the tags would be gone when you want to roll-back.  You would still have to record the digest in order to actually roll back.
